name: Nuget Test

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'jellyfin/jellyfin'
      
      # Runs a single command using the runners shell
      - run: dotnet restore JellyFin.sln --verbosity detailed
