name: Nuget Test

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'jellyfin/jellyfin'
      
      - run: ls -a
      - run: dotnet restore Jellyfin.sln --verbosity detailed > nugetoutput.txt
      - run: grep "GET " < nugetoutput.txt
      - run: grep "GET " < nugetoutput.txt | wc -l
      - run: dotnet nuget locals all --clear
      - run: dotnet restore Jellyfin.sln --verbosity detailed --force
      - run: conntrack --dump conntrack
