name: Test inputs

on:
  workflow_dispatch:
    inputs:
      the_number:
        description: 'Random number'
        required: true
        type: number
  
  issues:
    types: opened
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the argument via shell
        run: echo ${{ github.event.inputs.the_number }}

      - name: Dump the argument
        uses: actions/github-script@v7
        with:
          script: |
            const theNumber = context.payload?.inputs?.the_number
            console.log("The number: ")
            console.log(theNumber)

            console.log("JSON.stringify(context):") 
            console.log(JSON.stringify(context)) 

      - name: Dump the event name
        run: echo ${{ github.event_name }}
        
      - name: Run if an issue was opened
        if: ${{ github.event_name }} # only if this was started from an issue event
        run: echo Yay
