name: Test inputs

on:
  workflow_dispatch:
    inputs:
      the_number:
        description: 'Random number'
        required: true
        type: number
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the argument via shell
        run: echo ${{ github.event.inputs.the_number }}

      - name: Dump the argument
        uses: actions/github-script@v7
        with:
          script: |
            const theNumber = ${{ github.event.inputs.the_number }}
            console.log("The number: ")
            console.log(theNumber)

            console.log("JSON.stringify(context):") 
            console.log(JSON.stringify(context)) 
         
